### ISSUE TITLE
Last changes to nerdGraph causes tests to fail

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-integration-e2e-action#10]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Seems like we are requesting a deprecated field: https://github.com/newrelic/newrelic-prometheus-exporters-packages/runs/4326172884?check_suite_focus=true#step:5:146

## Steps to Reproduce

Run e2e action.

## Expected Behavior

Action should not error

## Relevant Logs / Console output

```
time="2021-11-25T16:21:12Z" level=error msg="finding entity guid: get entity: This field is deprecated! Please use `relatedEntities` instead."
time="2021-11-25T16:21:12Z" level=error msg="finding entity guid: get entity: This field is deprecated! Please use `relatedEntities` instead."
time="2021-11-25T16:21:42Z" level=warning msg="Error detected" iteration=7
```

## Additional context

There seems to be a PR to `client-go` that would cause this error to not be fatal: https://github.com/newrelic/newrelic-client-go/pull/839

However I think it would be better to avoid using deprecated fields if possible.

**Comment by gsanchezgavier** [comment]
This was fixed in #11 
now client go is on v0.69 and the issue was solve in [v0.68](https://github.com/newrelic/newrelic-client-go/releases/tag/v0.68.2)
