### ISSUE TITLE
using license as environment variable

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/newrelic-integration-e2e-action#8]
Currently the action to use commands making use of the license need to have it passed as an env var even if it is already present as a config arg.

This is not affecting ci/cd since the license is always passed already, but running it manually leads to a cumbersome command:

```
LICENSE_KEY=${LICENSE_KEY} newrelic-integration-e2e --commit_sha=test-string --retry_attempts=5 --retry_seconds=60 --license_key...
```

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
