### ISSUE TITLE
Change commit sha used to generate the unique tag

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/newrelic-integration-e2e-action#9]
Currently a commit sha it is used to generate the tests. 
However, that in the PRs is not the commit hash that triggered the PR, but the commit that would result from the merge of the PR and the base. This makes linking the old data with the differents commits of the PR really difficult

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
